name: dart_bbcode_parser
description: BBCode parser written in pure dart
version: 0.1.0
repository: https://github.com/realth000/dart_bbcode_parser
homepage: https://github.com/realth000/dart_bbcode_parser
publish_to: none

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  # path: ^1.8.0

dev_dependencies:
  # Blocked by pyramid_lint
  custom_lint: ^0.6.10
  lints: ^5.1.1
  pyramid_lint: ^2.0.1
  test: ^1.25.14
  very_good_analysis: ^7.0.0
