name: dart_bbcode_parser
description: BBCode parser written in pure dart
version: 0.1.0
repository: https://github.com/realth000/dart_bbcode_parser
homepage: https://github.com/realth000/dart_bbcode_parser
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  dart_bbcode_web_colors:
    path: ../dart_bbcode_web_colors
  # TODO: Separate quill related dependency to another package.
  dart_quill_delta: ^10.8.3
  dart_quill_delta_simplify: ^10.8.7
  meta: ^1.16.0
  string_scanner: ^1.4.1

dev_dependencies:
  custom_lint: ^0.7.3
  lints: ^5.1.1
  pyramid_lint: ^2.0.2
  test: ^1.25.14
  very_good_analysis: ^7.0.0
